### ISSUE TITLE
Improve design of planet-page.html

### ISSUE THREAD

**Issue by terrifricker** [terrifricker/our-solar-system#37]
planet-page.html can be a template of how each planet section would look after clicking on an index.html navigation planet.  It currently has no color and is partially responsive.

Currently at a width of 1100 px, the side by side layout made with flex box changes to a top and bottom layout.  At 1100px, I think it would look better if the Facts section was still side by side with the planet image, but the Details section would be below those two at full width.  This is only a suggestion.

Be creative and make any improvements you can imagine.

**Comment by juancwu** [comment]
I will take a look tomorrow and see where the ui can be improved.
